import type {
  DrugClass,
  MechanismDef,
  MechanismId,
  OrganismDef,
  Susceptibility,
} from '../../sim/infection/types';

/**
 * Organisms and resistance mechanisms for the Infectiology module (milestone 7) — educational, simplified
 * wild-type spectra and mechanism effects (EUCAST expected phenotypes / intrinsic resistance, summarised).
 * CLINICAL REVIEW: owner to confirm spectra, especially where clinical reliability differs from the test result.
 */

type ClassMap = Partial<Record<DrugClass, Susceptibility>>;

const all = (classes: DrugClass[], s: Susceptibility = 'R'): ClassMap =>
  Object.fromEntries(classes.map((c) => [c, s])) as ClassMap;

/** Agents with (practically) only Gram-positive activity — intrinsic R in Gram-negatives. */
const GRAM_POSITIVE_ONLY: DrugClass[] = [
  'penicillin',
  'isoxazolylpenicillin',
  'glycopeptide',
  'oxazolidinone',
  'lipopeptide',
  'lincosamide',
  'fidaxomicin',
  'rifamycin',
];
/** Agents without useful Gram-positive activity. */
const GRAM_NEGATIVE_ONLY: DrugClass[] = ['polymyxin', 'amidinopenicillin', 'siderophore-ceph'];
const ANTIFUNGALS: DrugClass[] = ['azole', 'echinocandin'];
const BETA_LACTAMS: DrugClass[] = [
  'penicillin',
  'aminopenicillin',
  'aminopenicillin-bli',
  'ureidopenicillin',
  'ureidopenicillin-bli',
  'isoxazolylpenicillin',
  'amidinopenicillin',
  'ceph1',
  'ceph2',
  'ceph3',
  'ceph3-antipseudomonal',
  'ceph4',
  'carbapenem-group1',
  'carbapenem',
  'new-bl-bli',
  'siderophore-ceph',
];
const ALL_ANTIBACTERIAL: DrugClass[] = [
  ...BETA_LACTAMS,
  'fluoroquinolone',
  'aminoglycoside',
  'glycopeptide',
  'oxazolidinone',
  'lipopeptide',
  'lincosamide',
  'nitroimidazole',
  'tetracycline',
  'glycylcycline',
  'macrolide',
  'folate-antagonist',
  'fosfomycin',
  'nitrofuran',
  'polymyxin',
  'fidaxomicin',
  'rifamycin',
];
/**
 * New β-lactam/β-lactamase-inhibitor combinations whose partner drug has no useful Gram-positive or anaerobic activity
 * (ceftazidime, ceftolozane, aztreonam). Meropenem-vaborbactam and imipenem-relebactam are deliberately absent: the
 * carbapenem component keeps its own spectrum (e.g. MSSA, B. fragilis); adding an inhibitor creates no resistance.
 * Whether they are a sensible or licensed choice for such organisms is a treatment question, not an S/I/R one.
 */
const NEW_BLBLI_GN_ONLY = {
  'ceftazidime-avibactam': 'R',
  'ceftolozane-tazobactam': 'R',
  'aztreonam-avibactam': 'R',
} as const;

const ENTEROBACTERALES_BASE: ClassMap = {
  ...all(GRAM_POSITIVE_ONLY),
  ...all(ANTIFUNGALS),
  nitroimidazole: 'R',
  macrolide: 'R',
  amidinopenicillin: 'S',
};

export const ORGANISMS: readonly OrganismDef[] = [
  {
    id: 'e-coli',
    nameKey: 'org.e-coli',
    group: 'enterobacterales',
    morphology: 'gnr',
    intrinsic: ENTEROBACTERALES_BASE,
    ttpH: 11,
  },
  {
    id: 'k-pneumoniae',
    nameKey: 'org.k-pneumoniae',
    group: 'enterobacterales',
    morphology: 'gnr',
    intrinsic: { ...ENTEROBACTERALES_BASE, aminopenicillin: 'R', ureidopenicillin: 'I' },
    ttpH: 12,
  },
  {
    id: 'e-cloacae',
    nameKey: 'org.e-cloacae',
    group: 'enterobacterales',
    morphology: 'gnr',
    // Expected resistant phenotype (chromosomal AmpC): aminopenicillins ± inhibitor, 1st/2nd-generation cephalosporins.
    intrinsic: {
      ...ENTEROBACTERALES_BASE,
      aminopenicillin: 'R',
      'aminopenicillin-bli': 'R',
      ceph1: 'R',
      ceph2: 'R',
    },
    chromosomal: ['ampc-inducible'],
    ttpH: 12,
  },
  {
    id: 'p-mirabilis',
    nameKey: 'org.p-mirabilis',
    group: 'enterobacterales',
    morphology: 'gnr',
    intrinsic: {
      ...ENTEROBACTERALES_BASE,
      polymyxin: 'R',
      nitrofuran: 'R',
      tetracycline: 'R',
      glycylcycline: 'R',
    },
    intrinsicDrugs: { imipenem: 'I' },
    ttpH: 12,
  },
  {
    id: 'p-aeruginosa',
    nameKey: 'org.p-aeruginosa',
    group: 'pseudomonas',
    morphology: 'gnr',
    intrinsic: {
      ...all(GRAM_POSITIVE_ONLY),
      ...all(ANTIFUNGALS),
      aminopenicillin: 'R',
      'aminopenicillin-bli': 'R',
      amidinopenicillin: 'R',
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'carbapenem-group1': 'R',
      nitroimidazole: 'R',
      tetracycline: 'R',
      glycylcycline: 'R',
      macrolide: 'R',
      'folate-antagonist': 'R',
      nitrofuran: 'R',
    },
    intrinsicDrugs: { moxifloxacin: 'R', 'fosfomycin-po': 'R' },
    ttpH: 16,
  },
  {
    id: 'a-baumannii',
    nameKey: 'org.a-baumannii',
    group: 'acinetobacter',
    morphology: 'gnr-small',
    intrinsic: {
      ...all(GRAM_POSITIVE_ONLY),
      ...all(ANTIFUNGALS),
      aminopenicillin: 'R',
      amidinopenicillin: 'R',
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'carbapenem-group1': 'R',
      nitroimidazole: 'R',
      fosfomycin: 'R',
      nitrofuran: 'R',
      macrolide: 'R',
    },
    // Sulbactam itself is active against A. baumannii.
    // Doxycycline activity is not inferred from minocycline/tigecycline activity.
    intrinsicDrugs: {
      'amoxicillin-clavulanate': 'R',
      'aztreonam-avibactam': 'R',
      doxycycline: 'R',
    },
    ttpH: 14,
  },
  {
    id: 's-maltophilia',
    nameKey: 'org.s-maltophilia',
    group: 'stenotrophomonas',
    morphology: 'gnr',
    intrinsic: {
      ...all(BETA_LACTAMS),
      ...all(GRAM_POSITIVE_ONLY),
      ...all(ANTIFUNGALS),
      aminoglycoside: 'R',
      nitroimidazole: 'R',
      macrolide: 'R',
      fosfomycin: 'R',
      nitrofuran: 'R',
      tetracycline: 'I',
    },
    // Cefiderocol or aztreonam-avibactam activity is not guaranteed by species identity (no EUCAST breakpoints):
    // they stay under the class default and are not reported on the panel.
    intrinsicDrugs: {
      ciprofloxacin: 'R',
      moxifloxacin: 'I',
    },
    ttpH: 18,
  },
  {
    id: 's-aureus',
    nameKey: 'org.s-aureus',
    group: 'staphylococcus',
    morphology: 'gpc-clusters',
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      'ceph3-antipseudomonal': 'R',
      nitroimidazole: 'R',
      fidaxomicin: 'R',
      aminoglycoside: 'S',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY },
    ttpH: 12,
  },
  {
    id: 'cons',
    nameKey: 'org.cons',
    group: 'staphylococcus',
    morphology: 'gpc-clusters',
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      'ceph3-antipseudomonal': 'R',
      nitroimidazole: 'R',
      fidaxomicin: 'R',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY },
    ttpH: 22,
    contaminant: true,
  },
  {
    id: 's-pneumoniae',
    nameKey: 'org.s-pneumoniae',
    group: 'streptococcus',
    morphology: 'gpc-pairs',
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      aminoglycoside: 'R',
      nitroimidazole: 'R',
      isoxazolylpenicillin: 'R',
      'ceph3-antipseudomonal': 'I',
      fidaxomicin: 'R',
      nitrofuran: 'R',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY, ciprofloxacin: 'I' },
    ttpH: 14,
  },
  {
    id: 's-pyogenes',
    nameKey: 'org.s-pyogenes',
    group: 'streptococcus',
    morphology: 'gpc-chains',
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      aminoglycoside: 'R',
      nitroimidazole: 'R',
      'ceph3-antipseudomonal': 'I',
      fidaxomicin: 'R',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY, ciprofloxacin: 'I' },
    ttpH: 12,
  },
  {
    id: 'viridans-strep',
    nameKey: 'org.viridans-strep',
    group: 'streptococcus',
    morphology: 'gpc-chains',
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      aminoglycoside: 'R',
      nitroimidazole: 'R',
      'ceph3-antipseudomonal': 'I',
      fidaxomicin: 'R',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY, ciprofloxacin: 'I' },
    ttpH: 18,
  },
  {
    id: 'e-faecalis',
    nameKey: 'org.e-faecalis',
    group: 'enterococcus',
    morphology: 'gpc-chains',
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'ceph3-antipseudomonal': 'R',
      ceph4: 'R',
      'carbapenem-group1': 'R',
      isoxazolylpenicillin: 'R',
      'folate-antagonist': 'R',
      lincosamide: 'R',
      // Intrinsic low-level aminoglycoside resistance: no monotherapy. Synergy with a cell-wall agent needs the absence
      // of high-level resistance (mechanism 'hlar'); SIM-ASSUMPTION: synergy itself is not modelled.
      aminoglycoside: 'R',
      macrolide: 'R',
      nitroimidazole: 'R',
      fluoroquinolone: 'I',
      fidaxomicin: 'R',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY, meropenem: 'I', 'meropenem-vaborbactam': 'I' },
    ttpH: 14,
  },
  {
    id: 'e-faecium',
    nameKey: 'org.e-faecium',
    group: 'enterococcus',
    morphology: 'gpc-chains',
    // Ampicillin resistance is common but isolate-dependent (mechanism 'pbp5'), not a species rule.
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'ceph3-antipseudomonal': 'R',
      ceph4: 'R',
      'carbapenem-group1': 'R',
      carbapenem: 'R',
      isoxazolylpenicillin: 'R',
      'folate-antagonist': 'R',
      lincosamide: 'R',
      aminoglycoside: 'R',
      macrolide: 'R',
      nitroimidazole: 'R',
      fluoroquinolone: 'R',
      fidaxomicin: 'R',
    },
    intrinsicDrugs: {
      ...NEW_BLBLI_GN_ONLY,
      'meropenem-vaborbactam': 'R',
      'imipenem-relebactam': 'R',
    },
    ttpH: 14,
  },
  {
    id: 'b-fragilis',
    nameKey: 'org.b-fragilis',
    group: 'anaerobe',
    morphology: 'gnr',
    intrinsic: {
      ...all(ANTIFUNGALS),
      aminoglycoside: 'R',
      penicillin: 'R',
      aminopenicillin: 'R',
      ureidopenicillin: 'R',
      isoxazolylpenicillin: 'R',
      amidinopenicillin: 'R',
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'ceph3-antipseudomonal': 'R',
      ceph4: 'R',
      fluoroquinolone: 'R',
      'folate-antagonist': 'R',
      glycopeptide: 'R',
      oxazolidinone: 'R',
      lipopeptide: 'R',
      polymyxin: 'R',
      fosfomycin: 'R',
      nitrofuran: 'R',
      macrolide: 'R',
      fidaxomicin: 'R',
      rifamycin: 'R',
      'siderophore-ceph': 'R',
    },
    intrinsicDrugs: { moxifloxacin: 'I', ...NEW_BLBLI_GN_ONLY },
    ttpH: 30,
  },
  {
    id: 'l-pneumophila',
    nameKey: 'org.l-pneumophila',
    group: 'atypical',
    morphology: 'gnr-small',
    // Intracellular: β-lactams, aminoglycosides and glycopeptides do not work clinically.
    intrinsic: {
      ...all(ALL_ANTIBACTERIAL),
      ...all(ANTIFUNGALS),
      fluoroquinolone: 'S',
      macrolide: 'S',
      tetracycline: 'S',
      rifamycin: 'S',
    },
    ttpH: 96,
    noRoutineCulture: true,
  },
  {
    id: 'l-monocytogenes',
    nameKey: 'org.l-monocytogenes',
    group: 'other',
    morphology: 'gpr',
    // Intrinsically resistant to all cephalosporins; aminopenicillins (± gentamicin) or cotrimoxazole work.
    intrinsic: {
      ...all(GRAM_NEGATIVE_ONLY),
      ...all(ANTIFUNGALS),
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'ceph3-antipseudomonal': 'R',
      ceph4: 'R',
      'siderophore-ceph': 'R',
      isoxazolylpenicillin: 'R',
      lincosamide: 'R',
      nitroimidazole: 'R',
      fidaxomicin: 'R',
      fluoroquinolone: 'I',
      fosfomycin: 'R',
    },
    intrinsicDrugs: { ...NEW_BLBLI_GN_ONLY },
    ttpH: 24,
  },
  {
    id: 'p-multocida',
    nameKey: 'org.p-multocida',
    group: 'other',
    morphology: 'gnr-small',
    intrinsic: {
      ...all(ANTIFUNGALS),
      isoxazolylpenicillin: 'R',
      ceph1: 'I',
      lincosamide: 'R',
      glycopeptide: 'R',
      oxazolidinone: 'R',
      lipopeptide: 'R',
      fidaxomicin: 'R',
      nitroimidazole: 'R',
      aminoglycoside: 'R',
      macrolide: 'I',
    },
    ttpH: 20,
  },
  {
    id: 'c-difficile',
    nameKey: 'org.c-difficile',
    group: 'cdiff',
    morphology: 'gpr',
    // Not an antibiogram: C. difficile is never cultured or tested here (noRoutineCulture). This map encodes only CDI
    // treatment suitability in the gut lumen (oral vancomycin, fidaxomicin, metronidazole); collateral microbiome damage
    // is a separate drug property (microbiomeDamage).
    intrinsic: {
      ...all(ALL_ANTIBACTERIAL),
      ...all(ANTIFUNGALS),
      glycopeptide: 'S',
      fidaxomicin: 'S',
      nitroimidazole: 'S',
    },
    ttpH: 48,
    noRoutineCulture: true,
  },
  {
    id: 'c-albicans',
    nameKey: 'org.c-albicans',
    group: 'yeast',
    morphology: 'yeast',
    intrinsic: { ...all(ALL_ANTIBACTERIAL), azole: 'S', echinocandin: 'S' },
    ttpH: 30,
  },
  {
    id: 'c-glabrata',
    nameKey: 'org.c-glabrata',
    group: 'yeast',
    morphology: 'yeast',
    // Fluconazole: susceptible at increased exposure (wild type); other azoles are judged drug by drug.
    intrinsic: { ...all(ALL_ANTIBACTERIAL), echinocandin: 'S' },
    intrinsicDrugs: { fluconazole: 'I' },
    ttpH: 40,
  },
];

const ALL_EXCEPT_NEW: DrugClass[] = BETA_LACTAMS.filter(
  (c) => c !== 'new-bl-bli' && c !== 'siderophore-ceph',
);

export const MECHANISMS: readonly MechanismDef[] = [
  {
    id: 'penicillinase',
    labelKey: 'mech.penicillinase',
    classes: { penicillin: 'R', aminopenicillin: 'R', ureidopenicillin: 'R' },
  },
  {
    // Methicillin resistance (mecA/mecC): "MRSA" only in S. aureus; in CoNS it is methicillin-resistant CoNS.
    id: 'meca',
    labelKey: 'mech.meca',
    classes: all(ALL_EXCEPT_NEW),
    drugs: { 'meropenem-vaborbactam': 'R', 'imipenem-relebactam': 'R' },
    rapidTest: 'mecA',
  },
  {
    id: 'esbl',
    labelKey: 'mech.esbl',
    classes: {
      penicillin: 'R',
      aminopenicillin: 'R',
      ureidopenicillin: 'R',
      'aminopenicillin-bli': 'I',
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'ceph3-antipseudomonal': 'R',
      ceph4: 'R',
    },
    // SIM-ASSUMPTION: piperacillin-tazobactam may test S but is unreliable in ESBL bloodstream infection
    // (randomised evidence favours carbapenems); modelled as an activity cap.
    activityCap: {
      'piperacillin-tazobactam': 0.35,
      'amoxicillin-clavulanate': 0.3,
      'ampicillin-sulbactam': 0.3,
    },
    rapidTest: 'ctx-m',
  },
  {
    id: 'ampc-inducible',
    labelKey: 'mech.ampc-inducible',
    classes: { aminopenicillin: 'R', 'aminopenicillin-bli': 'R', ceph1: 'R', ceph2: 'R' },
  },
  {
    id: 'ampc-derepressed',
    labelKey: 'mech.ampc-derepressed',
    classes: {
      aminopenicillin: 'R',
      'aminopenicillin-bli': 'R',
      ureidopenicillin: 'R',
      'ureidopenicillin-bli': 'R',
      ceph1: 'R',
      ceph2: 'R',
      ceph3: 'R',
      'ceph3-antipseudomonal': 'R',
    },
  },
  // Mechanism drug entries describe what the enzyme does to that drug: 'S' means "not hydrolysed" — it never improves
  // the isolate's category (other mechanisms and the wild type still apply). A mechanism predicts likely activity of a
  // newer agent; the complete isolate phenotype decides.
  {
    id: 'kpc',
    labelKey: 'mech.kpc',
    classes: all(BETA_LACTAMS),
    drugs: {
      'ceftazidime-avibactam': 'S',
      'meropenem-vaborbactam': 'S',
      'imipenem-relebactam': 'S',
      'aztreonam-avibactam': 'S',
      cefiderocol: 'S',
    },
    carbapenemase: true,
    rapidTest: 'carbapenemase',
  },
  {
    id: 'oxa48',
    labelKey: 'mech.oxa48',
    classes: {
      penicillin: 'R',
      aminopenicillin: 'R',
      'aminopenicillin-bli': 'R',
      ureidopenicillin: 'R',
      'ureidopenicillin-bli': 'R',
      'carbapenem-group1': 'R',
      carbapenem: 'I',
    },
    drugs: {
      'meropenem-vaborbactam': 'R',
      'imipenem-relebactam': 'R',
      'ceftolozane-tazobactam': 'R',
    },
    activityCap: { meropenem: 0.3, imipenem: 0.3 },
    carbapenemase: true,
    rapidTest: 'carbapenemase',
  },
  {
    id: 'mbl',
    labelKey: 'mech.mbl',
    classes: all(BETA_LACTAMS),
    drugs: { 'aztreonam-avibactam': 'S', cefiderocol: 'S' },
    // MBL P. aeruginosa usually carries further permeability/efflux mechanisms: aztreonam-avibactam evidence from MBL
    // Enterobacterales does not transfer.
    groupDrugs: { pseudomonas: { 'aztreonam-avibactam': 'R', cefiderocol: 'I' } },
    carbapenemase: true,
    rapidTest: 'carbapenemase',
  },
  {
    // OprD loss mainly affects imipenem; meropenem rises modestly unless further mechanisms add up.
    id: 'oprd-loss',
    labelKey: 'mech.oprd-loss',
    drugs: { imipenem: 'R', meropenem: 'I' },
  },
  {
    id: 'efflux',
    labelKey: 'mech.efflux',
    classes: {
      ureidopenicillin: 'R',
      'ureidopenicillin-bli': 'R',
      'ceph3-antipseudomonal': 'R',
      ceph4: 'R',
      fluoroquinolone: 'R',
    },
    // SIM-ASSUMPTION: one representative efflux phenotype (MexAB/MexXY overexpression), not a validated isolate set.
    drugs: { meropenem: 'I' },
  },
  { id: 'fq-resistance', labelKey: 'mech.fq-resistance', classes: { fluoroquinolone: 'R' } },
  {
    id: 'aminoglycoside-resistance',
    labelKey: 'mech.aminoglycoside-resistance',
    classes: { aminoglycoside: 'R' },
  },
  {
    // Enterococci: high-level aminoglycoside resistance — no synergy with a cell-wall agent.
    id: 'hlar',
    labelKey: 'mech.hlar',
    classes: { aminoglycoside: 'R' },
  },
  {
    // E. faecium: altered PBP5 — resistant to penicillins and carbapenems.
    id: 'pbp5',
    labelKey: 'mech.pbp5',
    classes: {
      penicillin: 'R',
      aminopenicillin: 'R',
      'aminopenicillin-bli': 'R',
      ureidopenicillin: 'R',
      'ureidopenicillin-bli': 'R',
      carbapenem: 'R',
    },
  },
  { id: 'vana', labelKey: 'mech.vana', classes: { glycopeptide: 'R' }, rapidTest: 'vanA' },
  {
    id: 'cotrim-resistance',
    labelKey: 'mech.cotrim-resistance',
    classes: { 'folate-antagonist': 'R' },
  },
  {
    id: 'macrolide-resistance',
    labelKey: 'mech.macrolide-resistance',
    classes: { macrolide: 'R' },
  },
  { id: 'clinda-resistance', labelKey: 'mech.clinda-resistance', classes: { lincosamide: 'R' } },
  {
    id: 'fluconazole-resistance',
    labelKey: 'mech.fluconazole-resistance',
    // Drug-specific: fluconazole resistance does not automatically make every azole resistant.
    drugs: { fluconazole: 'R' },
  },
];

export const ORGANISM_BY_ID: ReadonlyMap<string, OrganismDef> = new Map(
  ORGANISMS.map((o) => [o.id, o]),
);
export const MECHANISM_BY_ID: ReadonlyMap<MechanismId, MechanismDef> = new Map(
  MECHANISMS.map((m) => [m.id, m]),
);

/** Drugs the (fictional) lab reports per organism group — a simplified, non-cascaded panel. */
export const AST_PANELS: Partial<Record<OrganismDef['group'], readonly string[]>> = {
  enterobacterales: [
    'ampicillin',
    'amoxicillin-clavulanate',
    'piperacillin',
    'piperacillin-tazobactam',
    'cefuroxime',
    'cefotaxime',
    'ceftazidime',
    'cefepime',
    'ertapenem',
    'meropenem',
    'imipenem',
    'ciprofloxacin',
    'cotrimoxazole',
    'gentamicin',
    'fosfomycin-po',
    'nitrofurantoin',
    'pivmecillinam',
    'ceftazidime-avibactam',
    'meropenem-vaborbactam',
    'cefiderocol',
    'colistin',
  ],
  pseudomonas: [
    'piperacillin',
    'piperacillin-tazobactam',
    'ceftazidime',
    'cefepime',
    'meropenem',
    'imipenem',
    'ciprofloxacin',
    'levofloxacin',
    'tobramycin',
    'ceftolozane-tazobactam',
    'ceftazidime-avibactam',
    'imipenem-relebactam',
    'cefiderocol',
    'colistin',
  ],
  acinetobacter: [
    'ampicillin-sulbactam',
    'meropenem',
    'imipenem',
    'ciprofloxacin',
    'gentamicin',
    'cotrimoxazole',
    'tigecycline',
    'cefiderocol',
    'colistin',
  ],
  stenotrophomonas: ['cotrimoxazole', 'levofloxacin'],
  staphylococcus: [
    'penicillin-g',
    'flucloxacillin',
    'cefazolin',
    'clindamycin',
    'cotrimoxazole',
    'doxycycline',
    'levofloxacin',
    'gentamicin',
    'rifampicin',
    'vancomycin',
    'linezolid',
    'daptomycin',
  ],
  streptococcus: [
    'penicillin-g',
    'ampicillin',
    'ceftriaxone',
    'clindamycin',
    'clarithromycin',
    'levofloxacin',
    'vancomycin',
  ],
  enterococcus: [
    'ampicillin',
    'piperacillin-tazobactam',
    'imipenem',
    'vancomycin',
    'linezolid',
    'daptomycin',
    'nitrofurantoin',
    'tigecycline',
  ],
  anaerobe: [
    'amoxicillin-clavulanate',
    'piperacillin-tazobactam',
    'meropenem',
    'clindamycin',
    'metronidazole',
  ],
  other: [
    'penicillin-g',
    'ampicillin',
    'amoxicillin-clavulanate',
    'ceftriaxone',
    'doxycycline',
    'levofloxacin',
    'cotrimoxazole',
  ],
  yeast: ['fluconazole', 'anidulafungin'],
};
