import type { AntiinfectiveDef, DrugRoute, Focus } from '../../sim/infection/types';

/**
 * Anti-infective formulary for the Infectiology module (milestone 7) — educational data, not prescribing
 * information. Regimen texts (i18n) name the standard adult dose; the course model only distinguishes
 * reduced / standard / high exposure.
 *
 * Sources (in our own words): oral bioavailability from published pharmacology summaries as taught in the ABS
 * course (e.g. levofloxacin ≈ 99 %, linezolid ≈ 100 %, cotrimoxazole ≈ 100 %, metronidazole ≈ 99 %, clindamycin
 * ≈ 90 %, cefuroxime axetil ≈ 40 %, amoxicillin ≈ 70 %, flucloxacillin ≈ 50 %); penetration and biofilm activity
 * as relative educational factors.
 * CLINICAL REVIEW: doses, categories, penetration and costs must be confirmed by the owner.
 */

// SIM-ASSUMPTION: CO2 footprint — a non-quantitative game index, not a life-cycle assessment. One published estimate
// (Born et al., BMJ Qual Saf 2023) gives one week of ciprofloxacin as ≈ 100 kg CO2e i.v. (2 doses/day) versus ≈ 1.4 kg
// orally. We extrapolate ≈ 7 index units per i.v. dose and ≈ 0.2 per oral day to every drug, so courses can be
// compared by route and number of doses; real drug-specific footprints differ widely.
const co2 = (ivDosesPerDay: number | null, oral: boolean): Partial<Record<DrugRoute, number>> => ({
  ...(ivDosesPerDay !== null ? { iv: 7 * ivDosesPerDay } : {}),
  ...(oral ? { po: 0.2 } : {}),
});

/** Penetration profiles (0..1 relative effective exposure at the focus). SIM-ASSUMPTION: educational factors. */
const BETALACTAM: Partial<Record<Focus, number>> = { cns: 0.15, bone: 0.6, abdomen: 0.85, gut: 0 };
const BETALACTAM_CNS: Partial<Record<Focus, number>> = {
  cns: 0.7,
  bone: 0.6,
  abdomen: 0.85,
  gut: 0,
};
const QUINOLONE: Partial<Record<Focus, number>> = { cns: 0.5, bone: 0.9, gut: 0 };

export const ANTIINFECTIVES: readonly AntiinfectiveDef[] = [
  // ── Penicillins ──
  {
    id: 'penicillin-g',
    nameKey: 'abx.penicillin-g',
    drugClass: 'penicillin',
    category: 'access',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.5 },
    microbiomeDamage: 0.2,
    costPerDayEur: 15,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.penicillin-g',
  },
  {
    id: 'ampicillin',
    nameKey: 'abx.ampicillin',
    drugClass: 'aminopenicillin',
    category: 'access',
    routes: ['iv'],
    renallyCleared: true,
    penetration: BETALACTAM_CNS,
    microbiomeDamage: 0.4,
    costPerDayEur: 12,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.ampicillin',
  },
  {
    id: 'amoxicillin',
    nameKey: 'abx.amoxicillin',
    drugClass: 'aminopenicillin',
    category: 'access',
    routes: ['po'],
    bioavailability: 0.7,
    renallyCleared: true,
    penetration: BETALACTAM,
    microbiomeDamage: 0.35,
    costPerDayEur: 1,
    co2KgPerDay: co2(null, true),
    regimenKey: 'abx.reg.amoxicillin',
  },
  {
    id: 'amoxicillin-clavulanate',
    nameKey: 'abx.amoxicillin-clavulanate',
    drugClass: 'aminopenicillin-bli',
    category: 'access',
    routes: ['iv', 'po'],
    bioavailability: 0.7,
    renallyCleared: true,
    penetration: BETALACTAM,
    microbiomeDamage: 0.5,
    costPerDayEur: 10,
    co2KgPerDay: co2(3, true),
    regimenKey: 'abx.reg.amoxicillin-clavulanate',
  },
  {
    id: 'ampicillin-sulbactam',
    nameKey: 'abx.ampicillin-sulbactam',
    drugClass: 'aminopenicillin-bli',
    category: 'access',
    routes: ['iv'],
    renallyCleared: true,
    penetration: BETALACTAM,
    microbiomeDamage: 0.5,
    costPerDayEur: 18,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.ampicillin-sulbactam',
  },
  {
    // Lab marker only (KRINKO MRGN group "acylureidopenicillins"); not orderable in this simulator.
    id: 'piperacillin',
    nameKey: 'abx.piperacillin',
    drugClass: 'ureidopenicillin',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.2 },
    microbiomeDamage: 0.7,
    costPerDayEur: 0,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.piperacillin',
    labOnly: true,
  },
  {
    id: 'piperacillin-tazobactam',
    nameKey: 'abx.piperacillin-tazobactam',
    drugClass: 'ureidopenicillin-bli',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.2 },
    microbiomeDamage: 0.7,
    costPerDayEur: 30,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.piperacillin-tazobactam',
  },
  {
    id: 'flucloxacillin',
    nameKey: 'abx.flucloxacillin',
    drugClass: 'isoxazolylpenicillin',
    category: 'access',
    routes: ['iv'],
    renallyCleared: false,
    penetration: { ...BETALACTAM, cns: 0.2 },
    microbiomeDamage: 0.2,
    costPerDayEur: 25,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.flucloxacillin',
  },
  {
    id: 'pivmecillinam',
    nameKey: 'abx.pivmecillinam',
    drugClass: 'amidinopenicillin',
    category: 'access',
    routes: ['po'],
    bioavailability: 0.7,
    renallyCleared: true,
    // SIM-ASSUMPTION: used for lower urinary tract infection; little renal-tissue exposure at the cystitis dose.
    penetration: {
      blood: 0.3,
      lung: 0.2,
      abdomen: 0.2,
      skin: 0.2,
      bone: 0.1,
      valve: 0.1,
      cns: 0,
      gut: 0,
      line: 0.2,
      kidney: 0.3,
    },
    microbiomeDamage: 0.1,
    costPerDayEur: 3,
    co2KgPerDay: co2(null, true),
    regimenKey: 'abx.reg.pivmecillinam',
  },
  // ── Cephalosporins ──
  {
    id: 'cefazolin',
    nameKey: 'abx.cefazolin',
    drugClass: 'ceph1',
    category: 'access',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.05 },
    microbiomeDamage: 0.3,
    costPerDayEur: 12,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.cefazolin',
  },
  {
    id: 'cefuroxime',
    nameKey: 'abx.cefuroxime',
    drugClass: 'ceph2',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.4,
    renallyCleared: true,
    penetration: BETALACTAM,
    microbiomeDamage: 0.55,
    costPerDayEur: 10,
    co2KgPerDay: co2(3, true),
    regimenKey: 'abx.reg.cefuroxime',
  },
  {
    id: 'ceftriaxone',
    nameKey: 'abx.ceftriaxone',
    drugClass: 'ceph3',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: false,
    penetration: BETALACTAM_CNS,
    microbiomeDamage: 0.75,
    costPerDayEur: 5,
    co2KgPerDay: co2(1, false),
    regimenKey: 'abx.reg.ceftriaxone',
  },
  {
    id: 'cefotaxime',
    nameKey: 'abx.cefotaxime',
    drugClass: 'ceph3',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: BETALACTAM_CNS,
    microbiomeDamage: 0.7,
    costPerDayEur: 12,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.cefotaxime',
  },
  {
    id: 'ceftazidime',
    nameKey: 'abx.ceftazidime',
    drugClass: 'ceph3-antipseudomonal',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.4 },
    microbiomeDamage: 0.7,
    costPerDayEur: 25,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.ceftazidime',
  },
  {
    id: 'cefepime',
    nameKey: 'abx.cefepime',
    drugClass: 'ceph4',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.4 },
    microbiomeDamage: 0.7,
    costPerDayEur: 30,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.cefepime',
  },
  // ── Carbapenems ──
  {
    id: 'ertapenem',
    nameKey: 'abx.ertapenem',
    drugClass: 'carbapenem-group1',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: BETALACTAM,
    microbiomeDamage: 0.8,
    costPerDayEur: 50,
    co2KgPerDay: co2(1, false),
    regimenKey: 'abx.reg.ertapenem',
  },
  {
    id: 'meropenem',
    nameKey: 'abx.meropenem',
    drugClass: 'carbapenem',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: BETALACTAM_CNS,
    microbiomeDamage: 0.85,
    costPerDayEur: 40,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.meropenem',
  },
  {
    id: 'imipenem',
    nameKey: 'abx.imipenem',
    drugClass: 'carbapenem',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.3 },
    microbiomeDamage: 0.85,
    costPerDayEur: 45,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.imipenem',
  },
  // ── New β-lactam/β-lactamase-inhibitor combinations and cefiderocol (reserve) ──
  {
    id: 'ceftazidime-avibactam',
    nameKey: 'abx.ceftazidime-avibactam',
    drugClass: 'new-bl-bli',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.3 },
    microbiomeDamage: 0.8,
    costPerDayEur: 450,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.ceftazidime-avibactam',
  },
  {
    id: 'ceftolozane-tazobactam',
    nameKey: 'abx.ceftolozane-tazobactam',
    drugClass: 'new-bl-bli',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.2 },
    microbiomeDamage: 0.8,
    costPerDayEur: 400,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.ceftolozane-tazobactam',
  },
  {
    id: 'meropenem-vaborbactam',
    nameKey: 'abx.meropenem-vaborbactam',
    drugClass: 'new-bl-bli',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: BETALACTAM_CNS,
    microbiomeDamage: 0.85,
    costPerDayEur: 450,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.meropenem-vaborbactam',
  },
  {
    id: 'imipenem-relebactam',
    nameKey: 'abx.imipenem-relebactam',
    drugClass: 'new-bl-bli',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.3 },
    microbiomeDamage: 0.85,
    costPerDayEur: 450,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.imipenem-relebactam',
  },
  {
    id: 'aztreonam-avibactam',
    nameKey: 'abx.aztreonam-avibactam',
    drugClass: 'new-bl-bli',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.3 },
    microbiomeDamage: 0.6,
    costPerDayEur: 500,
    co2KgPerDay: co2(4, false),
    regimenKey: 'abx.reg.aztreonam-avibactam',
  },
  {
    id: 'cefiderocol',
    nameKey: 'abx.cefiderocol',
    drugClass: 'siderophore-ceph',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { ...BETALACTAM, cns: 0.3 },
    microbiomeDamage: 0.7,
    costPerDayEur: 600,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.cefiderocol',
  },
  // ── Fluoroquinolones ──
  {
    id: 'ciprofloxacin',
    nameKey: 'abx.ciprofloxacin',
    drugClass: 'fluoroquinolone',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.75,
    renallyCleared: true,
    penetration: QUINOLONE,
    biofilm: 0.7,
    microbiomeDamage: 0.6,
    costPerDayEur: 4,
    co2KgPerDay: co2(2, true),
    regimenKey: 'abx.reg.ciprofloxacin',
  },
  {
    id: 'levofloxacin',
    nameKey: 'abx.levofloxacin',
    drugClass: 'fluoroquinolone',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.99,
    renallyCleared: true,
    penetration: QUINOLONE,
    biofilm: 0.7,
    microbiomeDamage: 0.6,
    costPerDayEur: 4,
    co2KgPerDay: co2(1, true),
    regimenKey: 'abx.reg.levofloxacin',
  },
  {
    id: 'moxifloxacin',
    nameKey: 'abx.moxifloxacin',
    drugClass: 'fluoroquinolone',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.9,
    renallyCleared: false,
    penetration: { ...QUINOLONE, urine: 0.3, kidney: 0.5 },
    microbiomeDamage: 0.65,
    costPerDayEur: 5,
    co2KgPerDay: co2(1, true),
    regimenKey: 'abx.reg.moxifloxacin',
  },
  // ── Others ──
  {
    id: 'cotrimoxazole',
    nameKey: 'abx.cotrimoxazole',
    drugClass: 'folate-antagonist',
    category: 'access',
    routes: ['iv', 'po'],
    bioavailability: 1,
    renallyCleared: true,
    penetration: { cns: 0.5, bone: 0.8, gut: 0 },
    microbiomeDamage: 0.4,
    costPerDayEur: 2,
    co2KgPerDay: co2(2, true),
    regimenKey: 'abx.reg.cotrimoxazole',
  },
  {
    id: 'gentamicin',
    nameKey: 'abx.gentamicin',
    drugClass: 'aminoglycoside',
    category: 'access',
    routes: ['iv'],
    renallyCleared: true,
    nephrotoxic: true,
    tdm: true,
    penetration: { cns: 0.05, lung: 0.4, abdomen: 0.5, bone: 0.4, gut: 0 },
    microbiomeDamage: 0.2,
    costPerDayEur: 5,
    co2KgPerDay: co2(1, false),
    regimenKey: 'abx.reg.gentamicin',
  },
  {
    id: 'tobramycin',
    nameKey: 'abx.tobramycin',
    drugClass: 'aminoglycoside',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    nephrotoxic: true,
    tdm: true,
    penetration: { cns: 0.05, lung: 0.4, abdomen: 0.5, bone: 0.4, gut: 0 },
    microbiomeDamage: 0.2,
    costPerDayEur: 10,
    co2KgPerDay: co2(1, false),
    regimenKey: 'abx.reg.tobramycin',
  },
  {
    id: 'vancomycin',
    nameKey: 'abx.vancomycin',
    drugClass: 'glycopeptide',
    category: 'watch',
    routes: ['iv'],
    renallyCleared: true,
    nephrotoxic: true,
    tdm: true,
    penetration: { cns: 0.25, lung: 0.4, bone: 0.4, abdomen: 0.6, gut: 0 },
    biofilm: 0.3,
    microbiomeDamage: 0.15,
    costPerDayEur: 20,
    co2KgPerDay: co2(2, false),
    regimenKey: 'abx.reg.vancomycin',
  },
  {
    id: 'vancomycin-po',
    nameKey: 'abx.vancomycin-po',
    drugClass: 'glycopeptide',
    category: 'watch',
    routes: ['po'],
    // Not absorbed: acts only in the gut lumen.
    bioavailability: 0,
    renallyCleared: false,
    penetration: {
      blood: 0,
      lung: 0,
      urine: 0,
      abdomen: 0,
      skin: 0,
      bone: 0,
      valve: 0,
      cns: 0,
      line: 0,
      gut: 1,
      kidney: 0,
    },
    microbiomeDamage: 0.5,
    costPerDayEur: 40,
    co2KgPerDay: co2(null, true),
    regimenKey: 'abx.reg.vancomycin-po',
  },
  {
    id: 'fidaxomicin',
    nameKey: 'abx.fidaxomicin',
    drugClass: 'fidaxomicin',
    category: 'watch',
    routes: ['po'],
    bioavailability: 0,
    renallyCleared: false,
    penetration: {
      blood: 0,
      lung: 0,
      urine: 0,
      abdomen: 0,
      skin: 0,
      bone: 0,
      valve: 0,
      cns: 0,
      line: 0,
      gut: 1,
      kidney: 0,
    },
    // Narrow spectrum: spares much of the protective gut flora.
    microbiomeDamage: 0.1,
    costPerDayEur: 180,
    co2KgPerDay: co2(null, true),
    regimenKey: 'abx.reg.fidaxomicin',
  },
  {
    id: 'linezolid',
    nameKey: 'abx.linezolid',
    drugClass: 'oxazolidinone',
    category: 'reserve',
    routes: ['iv', 'po'],
    bioavailability: 1,
    renallyCleared: false,
    penetration: { cns: 0.7, bone: 0.6, gut: 0 },
    microbiomeDamage: 0.3,
    costPerDayEur: 60,
    co2KgPerDay: co2(2, true),
    regimenKey: 'abx.reg.linezolid',
  },
  {
    id: 'daptomycin',
    nameKey: 'abx.daptomycin',
    drugClass: 'lipopeptide',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    // Inactivated by surfactant: no effect in pneumonia.
    penetration: { lung: 0, cns: 0.1, bone: 0.6, gut: 0 },
    biofilm: 0.6,
    microbiomeDamage: 0.15,
    costPerDayEur: 120,
    co2KgPerDay: co2(1, false),
    regimenKey: 'abx.reg.daptomycin',
  },
  {
    id: 'clindamycin',
    nameKey: 'abx.clindamycin',
    drugClass: 'lincosamide',
    category: 'access',
    routes: ['iv', 'po'],
    bioavailability: 0.9,
    renallyCleared: false,
    penetration: { cns: 0.1, bone: 0.8, abdomen: 0.9, gut: 0 },
    // Highest C. difficile risk of the common agents.
    microbiomeDamage: 1,
    costPerDayEur: 10,
    co2KgPerDay: co2(3, true),
    regimenKey: 'abx.reg.clindamycin',
  },
  {
    id: 'metronidazole',
    nameKey: 'abx.metronidazole',
    drugClass: 'nitroimidazole',
    category: 'access',
    routes: ['iv', 'po'],
    bioavailability: 0.99,
    renallyCleared: false,
    penetration: { cns: 0.9, abdomen: 1, gut: 0.6 },
    microbiomeDamage: 0.4,
    costPerDayEur: 4,
    co2KgPerDay: co2(3, true),
    regimenKey: 'abx.reg.metronidazole',
  },
  {
    id: 'doxycycline',
    nameKey: 'abx.doxycycline',
    drugClass: 'tetracycline',
    category: 'access',
    routes: ['iv', 'po'],
    bioavailability: 0.9,
    renallyCleared: false,
    penetration: { cns: 0.3, urine: 0.4, gut: 0, kidney: 0.4 },
    microbiomeDamage: 0.3,
    costPerDayEur: 2,
    co2KgPerDay: co2(2, true),
    regimenKey: 'abx.reg.doxycycline',
  },
  {
    id: 'clarithromycin',
    nameKey: 'abx.clarithromycin',
    drugClass: 'macrolide',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.5,
    renallyCleared: true,
    penetration: { cns: 0.1, urine: 0.3, gut: 0, kidney: 0.3 },
    microbiomeDamage: 0.4,
    costPerDayEur: 3,
    co2KgPerDay: co2(2, true),
    regimenKey: 'abx.reg.clarithromycin',
  },
  {
    id: 'azithromycin',
    nameKey: 'abx.azithromycin',
    drugClass: 'macrolide',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.37,
    renallyCleared: false,
    penetration: { cns: 0.1, urine: 0.3, kidney: 0.3, gut: 0 },
    microbiomeDamage: 0.4,
    costPerDayEur: 3,
    co2KgPerDay: co2(1, true),
    regimenKey: 'abx.reg.azithromycin',
  },
  {
    id: 'fosfomycin-po',
    nameKey: 'abx.fosfomycin-po',
    drugClass: 'fosfomycin',
    // WHO AWaRe 2025: oral fosfomycin is a Watch antibiotic.
    category: 'watch',
    routes: ['po'],
    bioavailability: 0.4,
    renallyCleared: true,
    // SIM-ASSUMPTION: single oral dose for cystitis — bladder urine only, no renal-tissue or blood exposure.
    penetration: {
      blood: 0,
      lung: 0,
      abdomen: 0,
      skin: 0,
      bone: 0,
      valve: 0,
      cns: 0,
      gut: 0,
      line: 0,
      kidney: 0,
    },
    microbiomeDamage: 0.05,
    costPerDayEur: 8,
    co2KgPerDay: co2(null, true),
    regimenKey: 'abx.reg.fosfomycin-po',
  },
  {
    id: 'fosfomycin-iv',
    nameKey: 'abx.fosfomycin-iv',
    drugClass: 'fosfomycin',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    penetration: { cns: 0.5, bone: 0.7, gut: 0 },
    biofilm: 0.6,
    microbiomeDamage: 0.3,
    costPerDayEur: 80,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.fosfomycin-iv',
  },
  {
    id: 'nitrofurantoin',
    nameKey: 'abx.nitrofurantoin',
    drugClass: 'nitrofuran',
    category: 'access',
    routes: ['po'],
    bioavailability: 0.9,
    renallyCleared: true,
    penetration: {
      blood: 0,
      lung: 0,
      abdomen: 0,
      skin: 0,
      bone: 0,
      valve: 0,
      cns: 0,
      gut: 0,
      line: 0,
      kidney: 0,
    },
    microbiomeDamage: 0.05,
    costPerDayEur: 2,
    co2KgPerDay: co2(null, true),
    regimenKey: 'abx.reg.nitrofurantoin',
  },
  {
    id: 'colistin',
    nameKey: 'abx.colistin',
    drugClass: 'polymyxin',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: true,
    nephrotoxic: true,
    penetration: { cns: 0.05, lung: 0.4, bone: 0.4, gut: 0 },
    microbiomeDamage: 0.3,
    costPerDayEur: 60,
    co2KgPerDay: co2(3, false),
    regimenKey: 'abx.reg.colistin',
  },
  {
    id: 'tigecycline',
    nameKey: 'abx.tigecycline',
    drugClass: 'glycylcycline',
    category: 'reserve',
    routes: ['iv'],
    renallyCleared: false,
    // Low serum and urine levels: not for bloodstream or urinary infection.
    penetration: { blood: 0.3, urine: 0.1, cns: 0.1, gut: 0, kidney: 0.2 },
    microbiomeDamage: 0.5,
    costPerDayEur: 120,
    co2KgPerDay: co2(2, false),
    regimenKey: 'abx.reg.tigecycline',
  },
  {
    id: 'rifampicin',
    nameKey: 'abx.rifampicin',
    drugClass: 'rifamycin',
    category: 'watch',
    routes: ['iv', 'po'],
    bioavailability: 0.9,
    renallyCleared: false,
    penetration: { cns: 0.5, bone: 0.9, gut: 0 },
    biofilm: 1,
    microbiomeDamage: 0.2,
    costPerDayEur: 3,
    co2KgPerDay: co2(1, true),
    regimenKey: 'abx.reg.rifampicin',
  },
  // ── Antifungals ──
  {
    id: 'fluconazole',
    nameKey: 'abx.fluconazole',
    drugClass: 'azole',
    category: 'antifungal',
    routes: ['iv', 'po'],
    bioavailability: 0.9,
    renallyCleared: true,
    penetration: { cns: 0.8, abdomen: 0.85, gut: 0 },
    microbiomeDamage: 0.05,
    costPerDayEur: 5,
    co2KgPerDay: co2(1, true),
    regimenKey: 'abx.reg.fluconazole',
  },
  {
    id: 'anidulafungin',
    nameKey: 'abx.anidulafungin',
    drugClass: 'echinocandin',
    category: 'antifungal',
    routes: ['iv'],
    renallyCleared: false,
    // Poor peritoneal penetration (≈ 0.3) and none into CNS/urine.
    penetration: { cns: 0.05, urine: 0.05, abdomen: 0.3, gut: 0, kidney: 0.3 },
    microbiomeDamage: 0.05,
    costPerDayEur: 250,
    co2KgPerDay: co2(1, false),
    regimenKey: 'abx.reg.anidulafungin',
  },
];

export const ANTIINFECTIVE_BY_ID: ReadonlyMap<string, AntiinfectiveDef> = new Map(
  ANTIINFECTIVES.map((d) => [d.id, d]),
);
